{{- if .Values.metricsService.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "dunksense.fullname" . }}-metrics
  labels:
    {{- include "dunksense.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "dunksense.fullname" . }}-metrics
  minReplicas: {{ .Values.metricsService.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.metricsService.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.metricsService.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.metricsService.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.metricsService.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.metricsService.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max
{{- end }} 