apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dunksense.fullname" . }}-secret
  labels:
    {{- include "dunksense.labels" . | nindent 4 }}
type: Opaque
data:
  database-password: {{ .Values.secrets.database.password | b64enc }}
  redis-password: {{ .Values.secrets.redis.password | b64enc }}
  jwt-secret: {{ .Values.secrets.jwt.secret | b64enc }}
  openai-api-key: {{ .Values.secrets.openai.apiKey | b64enc }}
  firebase-service-account: {{ .Values.secrets.firebase.serviceAccount | b64enc }}

---
{{- if .Values.env.TLS_ENABLED }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dunksense.fullname" . }}-tls
  labels:
    {{- include "dunksense.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.cert | b64enc }}
  tls.key: {{ .Values.tls.key | b64enc }}
{{- end }} 