apiVersion: v2
name: dunksense
description: DunkSense AI Basketball Analytics Platform
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - basketball
  - analytics
  - ai
  - sports
  - machine-learning

maintainers:
  - name: DunkSense Team
    email: team@dunksense.ai

dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  
  - name: redis
    version: 17.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  
  - name: kafka
    version: 22.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
  
  - name: prometheus
    version: 23.x.x
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled
  
  - name: grafana
    version: 6.x.x
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled
  
  - name: jaeger
    version: 0.x.x
    repository: https://jaegertracing.github.io/helm-charts
    condition: tracing.jaeger.enabled

annotations:
  category: Analytics
  licenses: MIT 