# Production Environment Configuration
app:
  environment: production

# Metrics Service Configuration
metricsService:
  replicaCount: 5
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 20
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 70

# API Gateway Configuration
apiGateway:
  replicaCount: 3
  ingress:
    hosts:
      - host: api.dunksense.ai
        paths:
          - path: /
            pathType: Prefix
    annotations:
      nginx.ingress.kubernetes.io/rate-limit: "1000"
      nginx.ingress.kubernetes.io/rate-limit-burst: "2000"

# ML Pipeline Configuration
mlPipeline:
  replicaCount: 3
  resources:
    limits:
      cpu: 4000m
      memory: 8Gi
      nvidia.com/gpu: 2
    requests:
      cpu: 2000m
      memory: 4Gi

# Database Configuration
postgresql:
  architecture: replication
  primary:
    persistence:
      size: 100Gi
      storageClass: fast-ssd
    resources:
      limits:
        cpu: 2000m
        memory: 4Gi
      requests:
        cpu: 1000m
        memory: 2Gi
  readReplicas:
    replicaCount: 2
    persistence:
      size: 100Gi
      storageClass: fast-ssd
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi

# Redis Configuration
redis:
  architecture: replication
  master:
    persistence:
      size: 20Gi
      storageClass: fast-ssd
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
  replica:
    replicaCount: 2
    persistence:
      size: 20Gi
      storageClass: fast-ssd

# Kafka Configuration
kafka:
  replicaCount: 3
  persistence:
    size: 50Gi
    storageClass: fast-ssd
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 2Gi
  zookeeper:
    replicaCount: 3

# Monitoring Configuration
monitoring:
  prometheus:
    enabled: true
    server:
      persistentVolume:
        size: 50Gi
        storageClass: fast-ssd
      resources:
        limits:
          cpu: 2000m
          memory: 4Gi
        requests:
          cpu: 1000m
          memory: 2Gi
      retention: "30d"
  grafana:
    enabled: true
    persistence:
      size: 10Gi
      storageClass: fast-ssd

# Backup Configuration
backup:
  enabled: true
  schedule: "0 2 * * *"
  retention: "90d"
  destinations:
    s3:
      enabled: true
      bucket: "dunksense-production-backups"
      region: "us-west-2"

# Security Configuration
security:
  networkPolicies:
    enabled: true
  podSecurityPolicy:
    enabled: true

# Environment Variables
env:
  # Database Configuration
  DATABASE_MAX_CONNECTIONS: "200"
  DATABASE_MAX_IDLE_CONNECTIONS: "20"
  
  # TLS Configuration
  TLS_ENABLED: "true"

# Node Affinity for production workloads
nodeSelector:
  node-type: production

# Pod Anti-Affinity for high availability
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - dunksense
        topologyKey: kubernetes.io/hostname

# Tolerations for dedicated nodes
tolerations:
- key: "production"
  operator: "Equal"
  value: "true"
  effect: "NoSchedule" 